# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0003_auto_20170201_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
